### ISSUE TITLE
Does someone can write a simple demo project for new version?

### ISSUE THREAD

**Issue by chslink** [sukona/Grapevine#115]
Hi there,
  I had read the  online document,  it seems not completely done yet.A project as simple as "Hello world" is helpful.Thanks

**Comment by seeseekey** [comment]
Here you find a small demo:

https://seeseekey.net/archive/118328

**Comment by scottoffen** [comment]
While the project documentation is still being written, you can see a simple example in the source code in the [Grapevine.Local](https://github.com/sukona/Grapevine/tree/master/src/Grapevine.Local) project. I use the for doing simple integration testing right now, and its contents may vary, but I'll make sure there is always a working project in there.

**Comment by chslink** [comment]
thanks ,and does  `Grapevine` project base on .net 6? I try to run testcase but failed.

**Comment by scottoffen** [comment]
There shouldn't be a problem with using the .NET 6 language features, if that is what you mean. However, the DLL up on NuGet targets the .NET 4.0 framework. I have an item in my backlog to remedy that, but I wanted to get unit test coverage complete before doing that so that I know I haven't broken anything.

In the future, please use the [Gitter](https://gitter.im/sukona/Grapevine) room or [StackOverflow](http://stackoverflow.com/questions/tagged/grapevine?sort=newest) to ask questions about Grapevine. Only use Issues for defects, enhancements and feature requests.
