### ISSUE TITLE
How can I shut a server down remotely?

### ISSUE THREAD

**Issue by Costigan** [sukona/Grapevine#148]
I'm using version 4.  Grapevine v3 documentation has code sample:

```csharp
[RESTRoute(Method = HttpMethod.DELETE, PathInfo = @"^/shutdown$")]
public void HandleShutDownRequests(HttpListenerContext context)
{
    this.SendTextResponse(context, "shutting down");
    this.Server.Stop();
}
```

I believe this doesn't work in v4.  Server.Stop() doesn't return.

Currently, I put my initial thread in a loop, busy waiting for the server to halt.  I've created a boolean flag called StopRequest that causes this loop to exit after which Stop() is called.

This works, but it leaves my initial thread doing no work.  Is this busy wait the intended method?  (I say 'busy wait'.  The loop is sleeping most of the time, but it does loop back to test IsListening.)

How does this work with a REST cluster?  A cluster has no IsListening method.  Do you have sample code that shows how you recommend doing this?

**Comment by scottoffen** [comment]
As per [this issue](https://github.com/sukona/Grapevine/issues/40), a [new method](https://github.com/sukona/Grapevine/blob/master/src/Grapevine/Server/RestServer.cs#L267) was added in 4.0 to shut down servers remotely. Using your code sample above, its usage is very similar:

```csharp
[RestRoute(Method = HttpMethod.DELETE, PathInfo = @"^/shutdown$")]
public IHttpContext HandleShutDownRequests(IHttpContext context)
{
    context.Response.SendResponse("shutting down");
    context.Server.ThreadSafeStop();
}
```

As far as using this with a `RestCluster` -  and I'm assuming you want to shut down the entire cluster remotely - the route currently does not have access to the cluster (by default). You can get around this by setting a property on the server that holds a reference to the cluster, and then retrieving it from the server while inside your route, and call the `StopAll()`method on the cluster.

```csharp
// Wherever your server is configured
server.Properties["Cluster"] = restCluster;

// Inside your route
var cluster = context.Server.GetPropertyValueAs<RestCluster>("Cluster");
new Thread(cluster.StopAll).Start();
```

> Please note that I haven't actually tried any of this code, so some of the syntax might not be exact

The cluster doesn't have a thread-safe mechanism to stop all servers in a cluster. Are you making a feature request for that?

Otherwise, in the future, please ask questions like this in the [Gitter room](https://gitter.im/sukona/Grapevine) or on [StackOverflow](http://stackoverflow.com/questions/tagged/grapevine?sort=newest) (I get notified in each case), and reserve opening an issue on Github for defects, enhancements or feature requests. See the [Grapevine Support](https://github.com/sukona/Grapevine/blob/master/SUPPORT.md) page for more information.

**Comment by Costigan** [comment]
I'm not requesting a thread safe stop for the cluster.  I think the details of that are often application-specific, and following the pattern you've supplied is easy enough.  From a user's perspective, this issue was a small documentation problem (something documented in v3 was not documented to have changed in v4 ... that I could find).  But not having found it, I didn't know whether it was missing docs or a bug.  Thanks for pointing me to Glitter.  I'll use that for questions.

**Comment by scottoffen** [comment]
Yeah, sorry about that. The docs for 4.0 still need lots of updating.
