### ISSUE TITLE
PathInfo regex should not match on GET parameters

### ISSUE THREAD

**Issue by jarshwah** [sukona/Grapevine#16]
I'm of the opinion that routes should not take GET parameters into consideration when matching. Currently, the `PathInfo` is checked against `RawUrl` which includes GET parameters. This makes it hard to write effective routes, because order of parameters matter.

My routes are all starting to take this kind of shape, especially since they will be used in JSONP calls:

```
[RESTRoute(Method = HttpMethod.GET, PathInfo = @"^/poll/(\?[^/]*)?$")]
```

If users need to use GET parameters, then they should be extracted from within the route handler and validated there. `NotFound` can be returned on missing parameters.

Unfortunately, there aren't any properties that I can find on `context.Request` that expose just the `path` portion of the URL. If this is accepted, I'd probably split on `?` and take the first match.

Note that I'm actually using GrapevinePlus (great work by the way), but I figured that issues relating to both should be raised here.

Thanks.

**Comment by reppners** [comment]
+1

**Comment by scottoffen** [comment]
>Note that I'm actually using GrapevinePlus (great work by the way), but I figured that issues relating to both should be raised here

You are absolutely right. Issues that relate to both Grapevine and GrapevinePlus should be raised here.

**Comment by scottoffen** [comment]
While it certainly isn't uncommon for GET request to contain [query string](http://en.wikipedia.org/wiki/Query_string) parameters, let's first make sure we are using proper URI design. To quote from [O'Reilly's *RESTful Web Services*](http://shop.oreilly.com/product/9780596529260.do), page 233, under the header **URI Design** (emphasis mine):

>When designing URIs, use path variables to separate elements of a hierarchy, or a path through a directed graph. Example: `/weblogs/myweblog/entries/100` goes from the general to the specific. From a list of weblogs, to a particular weblog, to the entries in that weblog, to a particular entry. Each path variable is in some sense "inside" the previous one.
>
> Use punctuation characters to separate multiple pieces of data at the same level of hierarchy. Use commas when the order of the items matters, as it does in  latitude and longitude: `/Earth/37.0,-95.2`. Use semicolons when the order doesn't matter: `/color-blends/red;blue`.
>
>**Use query variables only to suggest arguments being plugged into an algorithm**, or when the other two techniques fail. If two URIs differ only in their query variables, it implies that they're the different sets of inputs into the same underlying algorithm.

The big takeaway here is that our URIs, generally speaking, should only use the query string to pass arguments to an algorithm. If, indeed, we are expecting query string parameters in our methods, those should be validated by the method the request is routed to, and our PathInfo regular expressions should reflect the possibility of receiving such arguments.

### Example : When not to use query string ###

Suppose you wanted to request user data given a specific numeric user id, let's say *632*. This is a scenario where it might be tempting to use the query string, but it would be better not to.

| Less Correct URI | More Correct URI |
|------------------|------------------|
| `/user?id=632`   | `/user/632`      |

The `RESTRoute` for the more-correct URI would then look like this:

```c#
[RESTRoute(Method = HttpMethod.GET, PathInfo = @"^/user/\d+$")]
public void GetUser(HttpListenerContext context)
{
	// GrabFirst is a String extension method that comes bundled with Grapevine
	// See https://github.com/scottoffen/Grapevine/wiki/Getting-Started-Syntactic-Sugar
	var userid = context.RawUrl.GrabFirst(@"^/user/(\d+)$");

	if (!object.ReferenceEquals(userid, null))
	{
		// you got your user id, do something
	}
	else
	{
		// invalid or missing user id
	}
}
```

### Example : Correctly using the query string ###

If you wanted to create a REST route that multiplied two integers together, then - setting aside that URI are suppose to represent resources, not operations on a resource - using a query string might be more suitable.

| Probably Less Correct URI | Probably More Correct URI   |
|---------------------------|-----------------------------|
| `/2/product/3`            | `/product?x=2&y=3`          |

The `RESTRoute` for the probably-more-correct URI would then look like this:

```c#
[RESTRoute(Method = HttpMethod.GET, PathInfo = @"^/product")]
public void MultiplyTwoIntegers(HttpListenerContext context)
{
	var x = context.Request.QueryString["x"];
	var y = context.Request.QueryString["y"];

	// I'll let you verify the inputs and do the math.
}
```

Note that the PathInfo regular expression omits the trailing `$`, which would normally indicate the end of the string, and we let the route method handle getting the parameters passed. If we really wanted to be a stickler, we could also write it like this:

```c#
[RESTRoute(Method = HttpMethod.GET, PathInfo = @"^/product\?.+$")]
```

Which would ensure that it at least looked like there might be some parameters coming in the query string, but isn't really necessary since we are going to do that checking anyway. If you are accepting an arbitrary number of parameters, we probably want to abstract the parameter retrieval out to another method.

If I've misunderstood your issue or if this example doesn't make sense, let me know. Meanwhile, although I agree with your assertion that

>[...] routes should not take GET parameters into consideration when matching.

This should be solved by properly constructing our URIs and regular expression, not via a code change or enhancement.

**Comment by jarshwah** [comment]
Let me provide a use-case that probably shouldn't be too uncommon; optionally supporting JSONP.

/weblogs/myweblog/entries/100/?callback=jsonp
/weblogs/myweblog/entries/?callback=jsonp

Now we *could* use CORS rather than JSONP for most browsers, but let us assume that JSONP is a viable method for cross domain ajax.

```
[RESTRoute(Method = HttpMethod.GET, PathInfo = @"^/weblogs/myweblog/entries/\d+/")]
[RESTRoute(Method = HttpMethod.GET, PathInfo = @"^/weblogs/myweblog/entries/")]
```

The problem above is that we explicitly need to order the methods in order to work around the lack of a trailing $ as a terminator. We can't have a terminating $ because there are now GET parameters we need to support. In this contrived case we only have a single GET parameter, but it's quite easy to imagine a situation where there are two or more.

If these URLs are in different types, then you're at the mercy of reflection loading the types in the correct order.

As a small data point, I'm unaware of any other routing library that includes query strings in route matching. I have not done an exhaustive search to confirm this though since it doesn't really matter too much.

I don't see any value added by including the query string in the PathInfo match, yet I see quite a lot of value in excluding the query string. I don't think the (simplified) argument of *get parameters aren't that useful to **real** RESTful webservices* is compelling in any way.

**Comment by scottoffen** [comment]
That's a fair point. Thank you for taking the time to explain a use case I had not considered; I now have a better understanding of the value add of this type of change.

**Comment by jarshwah** [comment]
Thanks! I appreciate you reconsidering.

**Comment by tekhedd** [comment]
Might I add that query parameters are required if the supplied values might contain forward slashes (ie, using names instead of numbers as unique IDs) . Even urlencoded, slashes tend to get unencoded en route/by the web server/etc, so am currently using url parameters in places where they do not represent queries or metadata. :(
