### ISSUE TITLE
StrongName Sign Grapevine Assemblies.

### ISSUE THREAD

**Issue by sodMetaldream** [sukona/Grapevine#176]
Nuget package of Grapewine+ is missing strong name. Is that by misstake or design?

Please add Stong name to the nugetpackage.....

**Comment by scottoffen** [comment]
1. Grapevine Plus (I'm assuming that's what you meant) has been deprecated. No further updates will be made.

2. I'm generally on board with strongly named assemblies. However:
  **a.** I (personally) haven't had a need for it
  **b.** I haven't had anyone ask me for it (you're the first)
  **c.** Private key management is pain point for open-source projects

Given that it has been a concise choice, i guess that means it's been by design. But it's not a design I'm not so married to that choice that I'm unwilling to reconsider. Certainly if it is hurting adoption rates (I have no evidence either way on this) then I'd find it worth the effort.

**Comment by sodMetaldream** [comment]
Ok Will switch to GrapeWine then. As all my projects are strong named the referenced assemblies need to as well. Thanks for a in all other way great projekt and swift answer.

**Comment by sodMetaldream** [comment]
All changed now running 4.0.0.252 (Nuget version) of Grapevine... Need the strong name though....

**Comment by scottoffen** [comment]
Grapevine is also not strongly named, but from the research I've done today, then as long as the strongly named assembly goes out in a major version, there really isn't a downside other than the effort on my part. Let do some more looking and see what this would take on my end.

**Comment by scottoffen** [comment]
From https://docs.microsoft.com/en-us/dotnet/standard/assembly/strong-named
>For .NET Core, strong-named assemblies do not provide material benefits.

Grapevine 5 does not target any .NET Framework versions, only netstandard and net5.0
