### ISSUE TITLE
Responding to Contexts outside of the Grapevine loop

### ISSUE THREAD

**Issue by jespertheend** [sukona/Grapevine#192]
Hello,

I have a game loop with a bunch of data that can ideally only be accessed from the main game loop thread. Is there an official way to do this. Right now I just store the context objects and respond to them from the main loop. I had to uncomment the `throw new RouteNotFoundException` part from Router.cs in order for this to work.
This sort of works, but I was wondering if there's a better approach that I don't know about.

**Comment by scottoffen** [comment]
Can you provide me with more context?

**Comment by jespertheend** [comment]
Sure, I ended up writing my own Rest service for the time being. So I don’t need this feature anymore, but perhaps other people might need it.

So basically I create a new Thread() with in it a while(true){} loop that runs all the game logic. I’m using a websocket library in another thread, but in order to make my life a lot easier I’m not parsing the received messages right away. I store them in a list instead. When I receive a message I lock(){} the list and put the message in that list. Then at the start of a cycle in the gameloop, I lock the list again, clone it, unlock it and then parse the messages in the cloned list. I do this because the variables I want to access from the message parsing code are not thread safe.

I had planned to do the same thing with Grapevine. So I tried storing all the `IHttpContext` in a list so I could `SendResponse` later in my gameloop, but if I do this it throws a `RouteNotFoundException` before I get the chance to call `SendResponse`.

**Comment by BenWoodford** [comment]
I wanted to do this as well as I'm working in Unity and a lot of APIs are locked to the main thread.

It's a bit of a hack but this does work, when you queue your context up to be handled on the main thread, use reflection to make the router think that the context has been handled but don't actually use `SendResponse` until you're on the main thread:

```
context.Response.GetType().GetProperty("ResponseSent").SetValue(context.Response, true);
```

The bit that does the actual disposing is `SendResponse` from what I can see, so the context will stay open until you then handle it on your thread.

**Comment by scottoffen** [comment]
Grapevine 5 (https://github.com/scottoffen/grapevine) is currently in beta. If you can provide me with a bare minimum code example of how this works (stick it somewhere on GitHub where I can pull it down) I'll look into this further. Keep in mind that I don't have much experience with Unity.

**Comment by BenWoodford** [comment]
> Grapevine 5 (https://github.com/scottoffen/grapevine) is currently in beta. If you can provide me with a bare minimum code example of how this works (stick it somewhere on GitHub where I can pull it down) I'll look into this further. Keep in mind that I don't have much experience with Unity.

My way's a bit of a hack, but the best way would be to have an option for the router not wait for a response and continue on, trusting whatever is handling it down the way before proceeding. I do this by hacking in a `ResponseSent = true` but the better way would be to have a separate (public) property that says the response will be on the backburner and handled later (and to trust the handler that it will be), so that it doesn't throw `RouteNotFoundException`

**Comment by scottoffen** [comment]
This is certainly an edge case, but I think I can make this happen easily, as long as it's understood that this would impact all requests when turned on. The behavior you are referring to is [implemented here](https://github.com/scottoffen/grapevine/blob/main/src/Grapevine/Router.cs#L84):


```csharp
await RouteAsync(context, RoutesFor(context));
if (!context.WasRespondedTo)
{
    if (context.Response.StatusCode == HttpStatusCode.Ok)
        context.Response.StatusCode = HttpStatusCode.NotImplemented;
    await HandleErrorAsync(context);
}
```

The point of which is primarily to catch scenarios where no routes are defined, and alert the client that their request isn't implemented. It serves secondarily as a good catch-all point if I want to just set the status code to something like "Bad Request", and let some global error handlers take care of the rest instead of defining that behavior everywhere else I want to use it.

So, what if we modified the signature of that awaited methods to return an int of the number of routes that were executed (I'm already tracking that). If it's zero, then we go with the not implemented error handler. If something was executed and the `HttpStatusCode` is still OK, I'll move on without returning an error.

```csharp
int executed = await RouteAsync(context, RoutesFor(context));
if (executed == 0 || context.HttpStatusCode != HttpStatusCode.Ok || (RequireResponseSent && !context.WasRespondedTo))
{
    if (context.Response.StatusCode == HttpStatusCode.Ok)
        context.Response.StatusCode = HttpStatusCode.NotImplemented;
    await HandleErrorAsync(context);
}
```

In this pseudo-implementation, `RequireResponseSent` is a new class variable I'll introduce that will default to true. This way, old behavior stays the same, and new behavior can be toggled on.

**Comment by scottoffen** [comment]
Here's how you turn it on in Grapevine 5:

```csharp
server.Router.ConfigureOptions((options) =>
{
    options.RequireRouteResponse = false;
});
```
