### ISSUE TITLE
RESTScope BasePath Property for DRY approach to have multiple service endpoints on one server/baseUrl

### ISSUE THREAD

**Issue by reppners** [sukona/Grapevine#21]
I would like to specify a base path that is appended to the base url which would provide a way to define separate service endpoints on my server with different implementations that are separated by RESTScope. Right now i would have to hardcode this in every RESTRoute regex attribute.

        [RESTScope(BasePath="myServiceBasePath"]

**Comment by scottoffen** [comment]
So, [RESTScope](https://github.com/scottoffen/Grapevine/wiki/Getting-Started-RestServer#scoping-restresource) is used to explicitly segregate/share resources between different servers listening at different host/port combinations. The [RESTRoute](https://github.com/scottoffen/Grapevine/wiki/Getting-Started-RestServer#responding-to-requests-with-data) maps incoming requests via the HTTP Method and PathInfo.

Do I understand correctly that you are looking to define some constants to be "inserted" between the BaseUrl on the RESTScope and the PathInfo on the RESTRoute - which *may* vary between scopes - so that you can both reduce the amount of information needed in the PathInfo regex attribute on the RESTRoute as well as reduce the number of RESTRoutes you'd need to decorate the method with?

If I've misunderstood, please clarify this for me with a use case and a usage example.

If I understand correctly, it's a non-trivial task, so I want to make certain I understand correctly what you're trying to accomplish.

### Example ###

```c#
[RESTScope(BaseUrl="http://localhost:1234", BasePath="library")]
[RESTScope(BaseUrl="http://localhost:4321", BasePath="bookstore")]
public sealed class MyResource : RESTResource
{
    [RESTRoute(Method = HttpMethod.GET, PathInfo = @"^/books/list$")]
    public void MyGetRoute(HttpListenerContext context)
    {
        this.SendTextResponse(context, "a list of books is returned here");
    }
}
````

Then a GET request to both of these URL would be routed to the same method:

- http://localhost:1234/library/books/list
- http://localhost:4321/bookstore/books/list

**Comment by reppners** [comment]
Yes, you do unterstand correctly. Though my use case at the moment is solely targeted to

scottoffen:
> [...] reduce the amount of information needed in the PathInfo regex attribute on the RESTRoute [...]

**Comment by scottoffen** [comment]
Ah, I see. Therefore, one could specify the BasePath but omit the BaseUrl.

### Example ###

```c#
[RESTScope(BasePath="library")]
public sealed class MyResource : RESTResource
{
    [RESTRoute(Method = HttpMethod.GET, PathInfo = @"/books/list$")]
    public void MyGetRoute1(HttpListenerContext context)
    {
        this.SendTextResponse(context, "a list of books is returned here");
    }

    [RESTRoute(Method = HttpMethod.GET, PathInfo = @"/book/\d+$")]
    public void MyGetRoute2(HttpListenerContext context)
    {
        this.SendTextResponse(context, "a single books is returned here");
    }
}
````

Would resolve to:

| C# Method | Http Method | Url |
|-----------|-------------|-----|
| GET       | MyGetRoute1 | http://localhost:1234/library/books/list |
| GET       | MyGetRoute2 | http://localhost:1234/library/book/1234 |

**Comment by scottoffen** [comment]
Completed in dev for 4.0
